//
//  LoginViewController.swift
//  Remote_Asset_Controller_iOS
//
//  Created berkehan ozturk on 4.02.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//
//

import UIKit

protocol LoginRouter: AnyObject {
    
}

protocol LoginView: BaseView {
    
}

class LoginViewController: BaseViewController {

    var presenter = LoginPresenter()

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }
    
}

extension LoginViewController: LoginView {
    
}

extension LoginViewController: LoginRouter {
    
}

