//
//  LoginPresenter.swift
//  Remote_Asset_Controller_iOS
//
//  Created berkehan ozturk on 4.02.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import UIKit

class LoginPresenter {

    weak var view: LoginView?
    weak var router: LoginRouter?
    
    func viewDidLoad() {
    }
    
}
